name: Update streak stats

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/streak-stats.yml"

concurrency:
  group: streak-stats-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Generate streak stats
        uses: DenverCoder1/github-readme-streak-stats@51cfb8879073b4c016ce6286016de0b14d179077 # v1.7.0
        with:
          options: user=${{ github.repository_owner }}&background=211E1E&ring=CFCECD&fire=ffffff&currStreakNum=CFCECD&sideNums=CFCECD&currStreakLabel=656363&sideLabels=656363&dates=4B4646&hide_border=true&disable_animations=true
          path: profile/streak.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit streak stats
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/streak.svg
          git commit -m "Update streak stats [skip ci]" || exit 0
          git push
